#:schema node_modules/wrangler/config-schema.json
name = "event-organizer-web"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-10-27"

[assets]
binding = "ASSETS"
directory = ".vercel/output/static"
html_handling = "worker"

[build]
command = "npm run worker:build"
